vim.opt.breakindent = true
vim.opt.clipboard = 'unnamedplus'
vim.opt.completeopt = "menu,menuone,noinsert,popup,fuzzy"
vim.opt.cursorline = true
vim.opt.cursorlineopt = "number"
vim.opt.foldlevelstart=99
vim.opt.ignorecase = true
vim.opt.linebreak = true
vim.opt.list = true
vim.opt.number = true
vim.opt.pumheight = 10
vim.opt.scrolloff = 2
vim.opt.sidescrolloff = 5
vim.opt.signcolumn = 'yes'
vim.opt.smartcase = true
vim.opt.softtabstop = -1
vim.opt.splitright = true
vim.opt.termguicolors = true
vim.opt.wildignore:append({ ".DS_Store" })
vim.opt.wildignorecase = true
vim.opt.wildmode = { "longest:full", "full" }
vim.opt.undofile = true
vim.opt.updatetime = 250
vim.opt.smoothscroll = true
